#!/usr/bin/env node
/**
 * Mirror every photo original to local disk.
 *
 *   node scripts/mirror-photos.mjs [--concurrency 6] [--verify]
 *
 * Pulls the 858 full-size originals out of the 2011 S3 bucket into data/photos/
 * (gitignored) and records size + sha256 for each in data/export/photos-manifest.json
 * (committed), so integrity is checkable later without the bucket.
 *
 * Only the full-size originals are mirrored. The 600px and 200px variants the old
 * site hand-cut are derivatives and get regenerated by the image pipeline - which
 * also makes the 209 photos missing a `med` variant stop being a special case.
 *
 * Resumable: a file already on disk with the expected size is skipped, so a failed
 * run can just be re-run. --verify re-hashes what is already there instead of
 * downloading.
 *
 * Note photo 1 ("The GMC") exists ONLY in the old repo's webroot - S3 returns 403
 * for it. It is the first photo on the site, and a naive S3-only mirror loses it.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, statSync, copyFileSync } from 'node:fs';
import { writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { dirname, resolve, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(ROOT, 'data/photos');
const MANIFEST = resolve(ROOT, 'data/export/photos-manifest.json');

/** Where the one non-S3 original lives. Overridable if the old repo moves. */
const LEGACY_WEBROOT = process.env.LEGACY_WEBROOT ||
  '/Users/paulcloutier/Sites/cake_13_sites/50states/html';

const arg = (name, dflt) => {
  const i = process.argv.indexOf(`--${name}`);
  return i > -1 ? process.argv[i + 1] : dflt;
};
const CONCURRENCY = Number(arg('concurrency', 6));
const VERIFY_ONLY = process.argv.includes('--verify');

const sha256 = (buf) => createHash('sha256').update(buf).digest('hex');

function targets() {
  const photos = JSON.parse(readFileSync(resolve(ROOT, 'data/export/photos.json'), 'utf8'));
  return photos
    .filter((p) => p.full)
    .map((p) => {
      const remote = /^https?:\/\//i.test(p.full);
      return {
        id: p.id,
        file: basename(p.full),
        source: remote ? p.full : resolve(LEGACY_WEBROOT, p.full.replace(/^\//, '')),
        remote,
      };
    });
}

async function fetchWithRetry(url, attempts = 4) {
  let lastErr;
  for (let i = 0; i < attempts; i++) {
    try {
      const res = await fetch(url);
      if (res.status === 403 || res.status === 404) {
        throw new Error(`HTTP ${res.status} (not in bucket)`);
      }
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      return Buffer.from(await res.arrayBuffer());
    } catch (e) {
      lastErr = e;
      if (/not in bucket/.test(e.message)) break;      // no point retrying
      await new Promise((r) => setTimeout(r, 400 * (i + 1)));
    }
  }
  throw lastErr;
}

async function handle(t, state) {
  const dest = resolve(OUT, t.file);

  if (existsSync(dest)) {
    const buf = readFileSync(dest);
    if (VERIFY_ONLY || buf.length > 0) {
      state.records.push({ id: t.id, file: t.file, bytes: buf.length, sha256: sha256(buf),
                           origin: t.remote ? 's3' : 'legacy-webroot' });
      state.skipped++;
      return;
    }
  }
  if (VERIFY_ONLY) { state.missing.push(t); return; }

  try {
    let buf;
    if (t.remote) {
      buf = await fetchWithRetry(t.source);
      await writeFile(dest, buf);
    } else {
      if (!existsSync(t.source)) throw new Error(`local file not found: ${t.source}`);
      copyFileSync(t.source, dest);
      buf = readFileSync(dest);
    }
    state.records.push({ id: t.id, file: t.file, bytes: buf.length, sha256: sha256(buf),
                         origin: t.remote ? 's3' : 'legacy-webroot' });
    state.done++;
  } catch (e) {
    state.failed.push({ id: t.id, file: t.file, source: t.source, error: e.message });
  }
}

async function main() {
  mkdirSync(OUT, { recursive: true });
  const list = targets();
  const state = { done: 0, skipped: 0, failed: [], missing: [], records: [] };

  console.log(`${VERIFY_ONLY ? 'Verifying' : 'Mirroring'} ${list.length} originals -> data/photos/`);

  const queue = [...list];
  let lastLog = 0;
  const worker = async () => {
    while (queue.length) {
      await handle(queue.shift(), state);
      const n = state.done + state.skipped + state.failed.length;
      if (n - lastLog >= 100) {
        lastLog = n;
        console.log(`  ${n}/${list.length} ...`);
      }
    }
  };
  await Promise.all(Array.from({ length: CONCURRENCY }, worker));

  state.records.sort((a, b) => a.id - b.id);
  const bytes = state.records.reduce((n, r) => n + r.bytes, 0);
  const bySource = state.records.reduce((m, r) => ({ ...m, [r.origin]: (m[r.origin] || 0) + 1 }), {});

  if (!VERIFY_ONLY) {
    writeFileSync(MANIFEST, JSON.stringify({
      generated: 'scripts/mirror-photos.mjs',
      count: state.records.length,
      totalBytes: bytes,
      bySource,
      files: state.records,
    }, null, 2) + '\n');
  }

  console.log(`\n  downloaded: ${state.done}`);
  console.log(`  already present: ${state.skipped}`);
  console.log(`  total: ${state.records.length} files, ${(bytes / 1024 / 1024).toFixed(0)} MB`);
  console.log(`  by source: ${JSON.stringify(bySource)}`);

  // Duplicate content is worth knowing about before paying to store it twice.
  const byHash = new Map();
  for (const r of state.records) {
    if (!byHash.has(r.sha256)) byHash.set(r.sha256, []);
    byHash.get(r.sha256).push(r.id);
  }
  const dupes = [...byHash.values()].filter((v) => v.length > 1);
  if (dupes.length) {
    console.log(`\n  identical files: ${dupes.length} groups`);
    dupes.slice(0, 5).forEach((g) => console.log(`    photo ids ${g.join(', ')}`));
  }

  if (state.failed.length) {
    console.log(`\n  FAILED: ${state.failed.length}`);
    state.failed.slice(0, 20).forEach((f) =>
      console.log(`    id=${f.id} ${f.file} - ${f.error}`));
    process.exitCode = 1;
  } else {
    console.log('\n  no failures.');
  }
}

main();
